DirectoryIndex index.php index.html index.htm

<VirtualHost *:80>
    ServerName localhost
    DocumentRoot "/usr/local/apache2/htdocs"
</VirtualHost>

<VirtualHost *:80>
    ServerName dev.local
    ServerAlias *.dev.local

    UseCanonicalName Off
    VirtualDocumentRoot "/var/www/%0/public"
    SetEnvIfNoCase X-Forwarded-Proto "^https$" HTTPS=on

    <Directory "/var/www">
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    <FilesMatch "\.php$">
        SetHandler "proxy:fcgi://php:9000"
    </FilesMatch>
</VirtualHost>
