# hello.dev.local virtual host
server {
    listen 80;
    listen [::]:80;
    server_name hello.dev.local;

    root /var/www/hello.dev.local/public;
    index index.html index.htm index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_index index.php;
    }

    location ~ /\.ht {
        deny all;
    }
}

# hello.dev.local HTTPS
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name hello.dev.local;

    ssl_certificate /etc/nginx/ssl/wildcard.crt;
    ssl_certificate_key /etc/nginx/ssl/wildcard.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/hello.dev.local/public;
    index index.html index.htm index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_index index.php;
    }

    location ~ /\.ht {
        deny all;
    }
}
